name: Publish

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack
        run: dotnet pack src/**/*.csproj
      - name: Publish
        run: dotnet nuget push src/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} 
